// source: autotimetabler.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.AutoTimetableResponse', null, global);
goog.exportSymbol('proto.TimetableConstraints', null, global);
goog.exportSymbol('proto.TimetableConstraints.Period', null, global);
goog.exportSymbol('proto.TimetableConstraints.Period.Class', null, global);
goog.exportSymbol('proto.TimetableConstraints.Period.Class.PeriodGroup', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TimetableConstraints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TimetableConstraints.repeatedFields_, null);
};
goog.inherits(proto.TimetableConstraints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TimetableConstraints.displayName = 'proto.TimetableConstraints';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TimetableConstraints.Period = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TimetableConstraints.Period.repeatedFields_, null);
};
goog.inherits(proto.TimetableConstraints.Period, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TimetableConstraints.Period.displayName = 'proto.TimetableConstraints.Period';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TimetableConstraints.Period.Class = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TimetableConstraints.Period.Class.repeatedFields_, null);
};
goog.inherits(proto.TimetableConstraints.Period.Class, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TimetableConstraints.Period.Class.displayName = 'proto.TimetableConstraints.Period.Class';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TimetableConstraints.Period.Class.PeriodGroup = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.TimetableConstraints.Period.Class.PeriodGroup, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TimetableConstraints.Period.Class.PeriodGroup.displayName = 'proto.TimetableConstraints.Period.Class.PeriodGroup';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AutoTimetableResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.AutoTimetableResponse.repeatedFields_, null);
};
goog.inherits(proto.AutoTimetableResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AutoTimetableResponse.displayName = 'proto.AutoTimetableResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TimetableConstraints.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TimetableConstraints.prototype.toObject = function(opt_includeInstance) {
  return proto.TimetableConstraints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TimetableConstraints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimetableConstraints.toObject = function(includeInstance, msg) {
  var f, obj = {
    start: jspb.Message.getFieldWithDefault(msg, 1, 0),
    end: jspb.Message.getFieldWithDefault(msg, 2, 0),
    days: jspb.Message.getFieldWithDefault(msg, 3, ""),
    gap: jspb.Message.getFieldWithDefault(msg, 4, 0),
    maxdays: jspb.Message.getFieldWithDefault(msg, 5, 0),
    periodsList: jspb.Message.toObjectList(msg.getPeriodsList(),
    proto.TimetableConstraints.Period.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TimetableConstraints}
 */
proto.TimetableConstraints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TimetableConstraints;
  return proto.TimetableConstraints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TimetableConstraints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TimetableConstraints}
 */
proto.TimetableConstraints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStart(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEnd(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDays(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGap(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxdays(value);
      break;
    case 6:
      var value = new proto.TimetableConstraints.Period;
      reader.readMessage(value,proto.TimetableConstraints.Period.deserializeBinaryFromReader);
      msg.addPeriods(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TimetableConstraints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TimetableConstraints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TimetableConstraints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimetableConstraints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStart();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getEnd();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getDays();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGap();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getMaxdays();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getPeriodsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.TimetableConstraints.Period.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TimetableConstraints.Period.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TimetableConstraints.Period.prototype.toObject = function(opt_includeInstance) {
  return proto.TimetableConstraints.Period.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TimetableConstraints.Period} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimetableConstraints.Period.toObject = function(includeInstance, msg) {
  var f, obj = {
    classesList: jspb.Message.toObjectList(msg.getClassesList(),
    proto.TimetableConstraints.Period.Class.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TimetableConstraints.Period}
 */
proto.TimetableConstraints.Period.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TimetableConstraints.Period;
  return proto.TimetableConstraints.Period.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TimetableConstraints.Period} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TimetableConstraints.Period}
 */
proto.TimetableConstraints.Period.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.TimetableConstraints.Period.Class;
      reader.readMessage(value,proto.TimetableConstraints.Period.Class.deserializeBinaryFromReader);
      msg.addClasses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TimetableConstraints.Period.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TimetableConstraints.Period.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TimetableConstraints.Period} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimetableConstraints.Period.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClassesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.TimetableConstraints.Period.Class.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TimetableConstraints.Period.Class.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TimetableConstraints.Period.Class.prototype.toObject = function(opt_includeInstance) {
  return proto.TimetableConstraints.Period.Class.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TimetableConstraints.Period.Class} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimetableConstraints.Period.Class.toObject = function(includeInstance, msg) {
  var f, obj = {
    periodgroupsList: jspb.Message.toObjectList(msg.getPeriodgroupsList(),
    proto.TimetableConstraints.Period.Class.PeriodGroup.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TimetableConstraints.Period.Class}
 */
proto.TimetableConstraints.Period.Class.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TimetableConstraints.Period.Class;
  return proto.TimetableConstraints.Period.Class.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TimetableConstraints.Period.Class} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TimetableConstraints.Period.Class}
 */
proto.TimetableConstraints.Period.Class.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.TimetableConstraints.Period.Class.PeriodGroup;
      reader.readMessage(value,proto.TimetableConstraints.Period.Class.PeriodGroup.deserializeBinaryFromReader);
      msg.addPeriodgroups(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TimetableConstraints.Period.Class.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TimetableConstraints.Period.Class.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TimetableConstraints.Period.Class} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimetableConstraints.Period.Class.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPeriodgroupsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.TimetableConstraints.Period.Class.PeriodGroup.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.prototype.toObject = function(opt_includeInstance) {
  return proto.TimetableConstraints.Period.Class.PeriodGroup.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TimetableConstraints.Period.Class.PeriodGroup} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.toObject = function(includeInstance, msg) {
  var f, obj = {
    day: jspb.Message.getFieldWithDefault(msg, 1, 0),
    starttime: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    endtime: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TimetableConstraints.Period.Class.PeriodGroup}
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TimetableConstraints.Period.Class.PeriodGroup;
  return proto.TimetableConstraints.Period.Class.PeriodGroup.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TimetableConstraints.Period.Class.PeriodGroup} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TimetableConstraints.Period.Class.PeriodGroup}
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDay(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setStarttime(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setEndtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TimetableConstraints.Period.Class.PeriodGroup.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TimetableConstraints.Period.Class.PeriodGroup} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDay();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getStarttime();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getEndtime();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
};


/**
 * optional int32 day = 1;
 * @return {number}
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.prototype.getDay = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.TimetableConstraints.Period.Class.PeriodGroup} returns this
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.prototype.setDay = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional float starttime = 2;
 * @return {number}
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.prototype.getStarttime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.TimetableConstraints.Period.Class.PeriodGroup} returns this
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.prototype.setStarttime = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float endtime = 3;
 * @return {number}
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.prototype.getEndtime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.TimetableConstraints.Period.Class.PeriodGroup} returns this
 */
proto.TimetableConstraints.Period.Class.PeriodGroup.prototype.setEndtime = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * repeated PeriodGroup periodGroups = 1;
 * @return {!Array<!proto.TimetableConstraints.Period.Class.PeriodGroup>}
 */
proto.TimetableConstraints.Period.Class.prototype.getPeriodgroupsList = function() {
  return /** @type{!Array<!proto.TimetableConstraints.Period.Class.PeriodGroup>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.TimetableConstraints.Period.Class.PeriodGroup, 1));
};


/**
 * @param {!Array<!proto.TimetableConstraints.Period.Class.PeriodGroup>} value
 * @return {!proto.TimetableConstraints.Period.Class} returns this
*/
proto.TimetableConstraints.Period.Class.prototype.setPeriodgroupsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.TimetableConstraints.Period.Class.PeriodGroup=} opt_value
 * @param {number=} opt_index
 * @return {!proto.TimetableConstraints.Period.Class.PeriodGroup}
 */
proto.TimetableConstraints.Period.Class.prototype.addPeriodgroups = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.TimetableConstraints.Period.Class.PeriodGroup, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.TimetableConstraints.Period.Class} returns this
 */
proto.TimetableConstraints.Period.Class.prototype.clearPeriodgroupsList = function() {
  return this.setPeriodgroupsList([]);
};


/**
 * repeated Class classes = 1;
 * @return {!Array<!proto.TimetableConstraints.Period.Class>}
 */
proto.TimetableConstraints.Period.prototype.getClassesList = function() {
  return /** @type{!Array<!proto.TimetableConstraints.Period.Class>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.TimetableConstraints.Period.Class, 1));
};


/**
 * @param {!Array<!proto.TimetableConstraints.Period.Class>} value
 * @return {!proto.TimetableConstraints.Period} returns this
*/
proto.TimetableConstraints.Period.prototype.setClassesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.TimetableConstraints.Period.Class=} opt_value
 * @param {number=} opt_index
 * @return {!proto.TimetableConstraints.Period.Class}
 */
proto.TimetableConstraints.Period.prototype.addClasses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.TimetableConstraints.Period.Class, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.TimetableConstraints.Period} returns this
 */
proto.TimetableConstraints.Period.prototype.clearClassesList = function() {
  return this.setClassesList([]);
};


/**
 * optional int32 start = 1;
 * @return {number}
 */
proto.TimetableConstraints.prototype.getStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.TimetableConstraints} returns this
 */
proto.TimetableConstraints.prototype.setStart = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 end = 2;
 * @return {number}
 */
proto.TimetableConstraints.prototype.getEnd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.TimetableConstraints} returns this
 */
proto.TimetableConstraints.prototype.setEnd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string days = 3;
 * @return {string}
 */
proto.TimetableConstraints.prototype.getDays = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.TimetableConstraints} returns this
 */
proto.TimetableConstraints.prototype.setDays = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 gap = 4;
 * @return {number}
 */
proto.TimetableConstraints.prototype.getGap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.TimetableConstraints} returns this
 */
proto.TimetableConstraints.prototype.setGap = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 maxdays = 5;
 * @return {number}
 */
proto.TimetableConstraints.prototype.getMaxdays = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.TimetableConstraints} returns this
 */
proto.TimetableConstraints.prototype.setMaxdays = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated Period periods = 6;
 * @return {!Array<!proto.TimetableConstraints.Period>}
 */
proto.TimetableConstraints.prototype.getPeriodsList = function() {
  return /** @type{!Array<!proto.TimetableConstraints.Period>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.TimetableConstraints.Period, 6));
};


/**
 * @param {!Array<!proto.TimetableConstraints.Period>} value
 * @return {!proto.TimetableConstraints} returns this
*/
proto.TimetableConstraints.prototype.setPeriodsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.TimetableConstraints.Period=} opt_value
 * @param {number=} opt_index
 * @return {!proto.TimetableConstraints.Period}
 */
proto.TimetableConstraints.prototype.addPeriods = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.TimetableConstraints.Period, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.TimetableConstraints} returns this
 */
proto.TimetableConstraints.prototype.clearPeriodsList = function() {
  return this.setPeriodsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.AutoTimetableResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AutoTimetableResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.AutoTimetableResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AutoTimetableResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AutoTimetableResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    timesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AutoTimetableResponse}
 */
proto.AutoTimetableResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AutoTimetableResponse;
  return proto.AutoTimetableResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AutoTimetableResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AutoTimetableResponse}
 */
proto.AutoTimetableResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addTimes(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AutoTimetableResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AutoTimetableResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AutoTimetableResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AutoTimetableResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimesList();
  if (f.length > 0) {
    writer.writePackedFloat(
      1,
      f
    );
  }
};


/**
 * repeated float times = 1;
 * @return {!Array<number>}
 */
proto.AutoTimetableResponse.prototype.getTimesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.AutoTimetableResponse} returns this
 */
proto.AutoTimetableResponse.prototype.setTimesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.AutoTimetableResponse} returns this
 */
proto.AutoTimetableResponse.prototype.addTimes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AutoTimetableResponse} returns this
 */
proto.AutoTimetableResponse.prototype.clearTimesList = function() {
  return this.setTimesList([]);
};


goog.object.extend(exports, proto);
